kind: Deployment
apiVersion: apps/v1

metadata:
  name: nginx-dep
  namespace: nginx-ns
  labels:
    app: nginx-dep-lb

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - name: nginx-pod
        image: nginx:latest
        ports:
          - containerPort: 80
