kind: HorizontalPodAutoscaler
apiVersion: autoscalling/v2

metadata:
  name: mysql-HPA
  namespace: mysql-ns

spec:
  scaleTargetRef:
  kind: Deployment
  apiVersion: apps/v1
  name: mysql-dep
  
  minReplicas: 1
  maxReplicas: 3

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
       type: Utilization
         averageUtilization: 2
